Repository STUDIO-EYE/STUDIO-EYE-SERVER, pull requests merged in 2024-10, with the labels that each got.

#3 Sprint4
  build.gradle
  src/main/java/studio/studioeye/StudioEyeApplication.java
  src/main/java/studio/studioeye/domain/client/dto/request/CreateClientServiceRequestDto.java
  src/main/java/studio/studioeye/domain/menu/api/MenuController.java
  src/main/java/studio/studioeye/domain/menu/application/MenuService.java
  src/main/java/studio/studioeye/domain/menu/dao/MenuRepository.java
  src/main/java/studio/studioeye/domain/menu/domain/Menu.java
  src/main/java/studio/studioeye/domain/menu/dto/request/CreateMenuRequestDto.java
  src/main/java/studio/studioeye/domain/menu/dto/request/CreateMenuServiceRequestDto.java
  src/main/java/studio/studioeye/domain/menu/dto/request/UpdateMenuRequestDto.java
  src/main/java/studio/studioeye/domain/menu/dto/request/UpdateMenuServiceRequestDto.java
  src/main/java/studio/studioeye/domain/recruitment/application/RecruitmentService.java
  src/main/java/studio/studioeye/domain/recruitment/dao/RecruitmentRepository.java
  src/main/java/studio/studioeye/domain/recruitment/domain/Recruitment.java
  src/main/java/studio/studioeye/domain/recruitment/dto/request/CreateRecruitmentRequestDto.java
  src/main/java/studio/studioeye/domain/recruitment/dto/request/CreateRecruitmentServiceRequestDto.java
  src/main/java/studio/studioeye/domain/recruitment/dto/request/UpdateRecruitmentRequestDto.java
  src/main/java/studio/studioeye/domain/recruitment/dto/request/UpdateRecruitmentServiceRequestDto.java
  src/main/java/studio/studioeye/global/exception/error/ErrorCode.java
Labels: :earth_americas: 인프라, 🔖버전, 🛠️ 리팩토링

#6 [TEST]: News 단일 조회 및 삭제 단위 테스트 작성 + Jacoco 설정
  build.gradle
  src/main/java/studio/studioeye/domain/request/api/RequestController.java
  src/main/java/studio/studioeye/domain/request/application/RequestService.java
  src/main/java/studio/studioeye/domain/request/dao/RequestCount.java
  src/main/java/studio/studioeye/domain/request/dao/RequestCountImpl.java
  src/main/java/studio/studioeye/domain/request/dao/RequestRepository.java
  src/main/java/studio/studioeye/domain/request/dao/RequestStateCount.java
  src/main/java/studio/studioeye/domain/request/dao/RequestStateCountImpl.java
  src/test/java/studio/studioeye/domain/news/application/NewsServiceTest.java
Labels: :recycle: 테스트

#7 [TEST] 뉴스 생성, 전체 조회, 리스트 삭제 단위 테스트
  src/test/java/studio/studioeye/StudioEyeApplicationTests.java
  src/test/java/studio/studioeye/domain/news/application/NewsServiceTest.java
Labels: :recycle: 테스트

#8 [TEST] 뉴스 페이지네이션 조회, 수정 단위 테스트 작성
  README.md
  src/test/java/studio/studioeye/domain/news/application/NewsServiceTest.java
Labels: :recycle: 테스트

#10 V.0.0.1
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  build.gradle
  src/main/java/studio/studioeye/domain/benefit/api/BenefitController.java
  src/main/java/studio/studioeye/domain/benefit/application/BenefitService.java
  src/main/java/studio/studioeye/domain/ceo/api/CeoController.java
  src/main/java/studio/studioeye/domain/menu/api/MenuController.java
  src/main/java/studio/studioeye/domain/menu/application/MenuService.java
  src/main/java/studio/studioeye/domain/menu/dao/MenuRepository.java
  src/main/java/studio/studioeye/domain/menu/domain/Menu.java
  src/main/java/studio/studioeye/domain/menu/domain/MenuTitle.java
  src/main/java/studio/studioeye/domain/menu/dto/request/CreateMenuRequestDto.java
  src/main/java/studio/studioeye/domain/menu/dto/request/CreateMenuServiceRequestDto.java
  src/main/java/studio/studioeye/domain/menu/dto/request/UpdateMenuRequestDto.java
  src/main/java/studio/studioeye/domain/menu/dto/request/UpdateMenuServiceRequestDto.java
  src/main/java/studio/studioeye/domain/project/domain/ArtworkCategory.java
  src/main/java/studio/studioeye/domain/recruitment/api/RecruitmentController.java
  src/main/java/studio/studioeye/domain/recruitment/application/RecruitmentService.java
  src/main/java/studio/studioeye/domain/recruitment/dao/RecruitmentRepository.java
  src/main/java/studio/studioeye/domain/recruitment/dao/RecruitmentTitle.java
  src/main/java/studio/studioeye/domain/recruitment/domain/Recruitment.java
  src/main/java/studio/studioeye/domain/recruitment/domain/Status.java
  src/main/java/studio/studioeye/domain/recruitment/dto/request/CreateRecruitmentServiceRequestDto.java
  src/main/java/studio/studioeye/domain/request/api/RequestController.java
  src/main/java/studio/studioeye/domain/request/application/RequestService.java
  src/main/java/studio/studioeye/domain/request/dao/AnswerRepository.java
  src/main/java/studio/studioeye/domain/request/dao/RequestCount.java
  src/main/java/studio/studioeye/domain/request/dao/RequestCountImpl.java
  src/main/java/studio/studioeye/domain/request/dao/RequestRepository.java
  src/main/java/studio/studioeye/domain/request/dao/RequestStateCount.java
  src/main/java/studio/studioeye/domain/request/dao/RequestStateCountImpl.java
  src/main/java/studio/studioeye/domain/request/dto/request/UpdateRequestCommentDto.java
  src/main/java/studio/studioeye/domain/request/dto/request/UpdateRequestStateDto.java
  src/main/java/studio/studioeye/domain/views/api/ViewsController.java
  src/main/java/studio/studioeye/domain/views/application/ViewsService.java
  src/main/java/studio/studioeye/domain/views/dao/ViewsRepository.java
  src/main/java/studio/studioeye/domain/views/dao/ViewsSummary.java
  src/main/java/studio/studioeye/domain/views/domain/Views.java
  src/main/java/studio/studioeye/domain/views/dto/request/CreateViewsRequestDto.java
  src/main/java/studio/studioeye/domain/views/dto/request/CreateViewsServiceRequestDto.java
  src/main/java/studio/studioeye/domain/views/dto/request/UpdateViewsRequestDto.java
  src/main/java/studio/studioeye/domain/views/dto/request/UpdateViewsServiceRequestDto.java
  src/main/java/studio/studioeye/global/exception/error/ErrorCode.java
  src/test/java/studio/studioeye/StudioEyeApplicationTests.java
  src/test/java/studio/studioeye/domain/news/application/NewsServiceTest.java
Labels: 🔖버전

#14 [TEST]: Menu Service 단위 테스트 작성
  src/main/java/studio/studioeye/domain/menu/application/MenuService.java
  src/main/java/studio/studioeye/domain/menu/dao/MenuRepository.java
  src/test/java/studio/studioeye/domain/menu/application/MenuServiceTest.java
Labels: :recycle: 테스트

#15 [TEST]: Recruitment Service 단위 테스트 작성
  src/main/java/studio/studioeye/domain/recruitment/application/RecruitmentService.java
  src/main/java/studio/studioeye/global/exception/error/ErrorCode.java
  src/test/java/studio/studioeye/domain/recruitment/application/RecruitmentServiceTest.java
Labels: :recycle: 테스트

#16 V.0.0.2
  src/main/java/studio/studioeye/domain/menu/application/MenuService.java
  src/main/java/studio/studioeye/domain/menu/dao/MenuRepository.java
  src/main/java/studio/studioeye/domain/recruitment/application/RecruitmentService.java
  src/main/java/studio/studioeye/domain/views/api/ViewsController.java
  src/main/java/studio/studioeye/domain/views/application/ViewsService.java
  src/main/java/studio/studioeye/global/exception/error/ErrorCode.java
  src/test/java/studio/studioeye/domain/benefit/application/BenefitServiceTest.java
  src/test/java/studio/studioeye/domain/menu/application/MenuServiceTest.java
  src/test/java/studio/studioeye/domain/recruitment/application/RecruitmentServiceTest.java
Labels: 🔖버전

#22 [TEST]: FAQ Service 단위 테스트 작성
  src/main/java/studio/studioeye/domain/faq/application/FaqService.java
  src/main/java/studio/studioeye/global/exception/error/ErrorCode.java
  src/test/java/studio/studioeye/domain/faq/application/FaqServiceTest.java
Labels: :recycle: 테스트

#23 [TEST]: Project Service 단위 테스트 작성
  src/test/java/studio/studioeye/domain/project/application/ProjectServiceTest.java
Labels: :recycle: 테스트

#24 [TEST]: Partner Information 단위 테스트 작성
  src/main/java/studio/studioeye/domain/partner_information/application/PartnerInformationService.java
  src/test/java/studio/studioeye/domain/partner_information/application/PartnerInformationServiceTest.java
  src/test/java/studio/studioeye/domain/project/application/ProjectServiceTest.java
Labels: :recycle: 테스트

#25 V.0.0.3
  build.gradle
  src/main/java/studio/studioeye/domain/ceo/api/CeoController.java
  src/main/java/studio/studioeye/domain/ceo/application/CeoService.java
  src/main/java/studio/studioeye/domain/company_information/api/CompanyInformationController.java
  src/main/java/studio/studioeye/domain/company_information/application/CompanyInformationService.java
  src/main/java/studio/studioeye/domain/company_information/dao/CompanyInformationRepository.java
  src/main/java/studio/studioeye/domain/company_information/domain/CompanyInformation.java
  src/main/java/studio/studioeye/domain/company_information/dto/request/CreateCompanyInformationServiceRequestDto.java
  src/main/java/studio/studioeye/domain/faq/application/FaqService.java
  src/main/java/studio/studioeye/domain/partner_information/application/PartnerInformationService.java
  src/main/java/studio/studioeye/global/exception/error/ErrorCode.java
  src/test/java/studio/studioeye/domain/ceo/application/CeoServiceTest.java
  src/test/java/studio/studioeye/domain/faq/application/FaqServiceTest.java
  src/test/java/studio/studioeye/domain/partner_information/application/PartnerInformationServiceTest.java
  src/test/java/studio/studioeye/domain/project/application/ProjectServiceTest.java
Labels: 🔖버전
