Repository STUDIO-EYE/STUDIO-EYE-SERVER, pull requests merged in 2024-11, with the labels that each got.

#29 [TEST]: User Service 단위 테스트 작성
  src/main/java/studio/studioeye/domain/user/application/UserService.java
  src/main/java/studio/studioeye/domain/user/application/UserServiceImpl.java
  src/test/java/studio/studioeye/domain/user/application/UserServiceImplTest.java
Labels: :recycle: 테스트

#30 Test/#28 client
  src/test/java/studio/studioeye/domain/client/application/ClientServiceTest.java
Labels: :recycle: 테스트

#31 [TEST]: Views Service 단위 테스트 작성
  src/main/java/studio/studioeye/domain/views/application/ViewsService.java
  src/test/java/studio/studioeye/domain/views/application/ViewsServiceTest.java
Labels: :recycle: 테스트

#32 V.0.0.4
  src/main/java/studio/studioeye/domain/ceo/api/CeoController.java
  src/main/java/studio/studioeye/domain/ceo/application/CeoService.java
  src/main/java/studio/studioeye/domain/ceo/dao/CeoRepository.java
  src/main/java/studio/studioeye/domain/ceo/domain/Ceo.java
  src/main/java/studio/studioeye/domain/faq/application/FaqService.java
  src/main/java/studio/studioeye/domain/project/api/ProjectController.java
  src/main/java/studio/studioeye/domain/project/application/ProjectService.java
  src/main/java/studio/studioeye/domain/project/dao/ProjectRepository.java
  src/main/java/studio/studioeye/domain/project/domain/Project.java
  src/main/java/studio/studioeye/domain/project/dto/request/CreateProjectServiceRequestDto.java
  src/main/java/studio/studioeye/domain/recruitment/dao/RecruitmentRepository.java
  src/main/java/studio/studioeye/domain/user/application/UserService.java
  src/main/java/studio/studioeye/domain/user/application/UserServiceImpl.java
  src/main/java/studio/studioeye/domain/views/application/ViewsService.java
  src/test/java/studio/studioeye/domain/client/application/ClientServiceTest.java
  src/test/java/studio/studioeye/domain/user/application/UserServiceImplTest.java
  src/test/java/studio/studioeye/domain/views/application/ViewsServiceTest.java
Labels: 🔖버전

#36 [TEST]: Views Service 단위 테스트 작성
  src/main/java/studio/studioeye/domain/views/application/ViewsService.java
  src/test/java/studio/studioeye/domain/views/application/ViewsServiceTest.java
Labels: :recycle: 테스트

#38 [TEST]: Notification, User Notification Service 단위 테스트 작성
  src/test/java/studio/studioeye/domain/notification/application/NotificationServiceTest.java
  src/test/java/studio/studioeye/domain/user_notification/application/UserNotificationServiceTest.java
Labels: :recycle: 테스트

#39 [TEST]: Company Information Service 단위 테스트 작성
  src/main/java/studio/studioeye/domain/company_information/application/CompanyInformationService.java
  src/test/java/studio/studioeye/domain/CompanyInformationServiceTest.java
Labels: :recycle: 테스트

#40 V.0.0.5
  src/main/java/studio/studioeye/domain/company_information/application/CompanyInformationService.java
  src/main/java/studio/studioeye/domain/views/api/ViewsController.java
  src/main/java/studio/studioeye/domain/views/application/ViewsService.java
  src/test/java/studio/studioeye/domain/CompanyInformationServiceTest.java
  src/test/java/studio/studioeye/domain/notification/application/NotificationServiceTest.java
  src/test/java/studio/studioeye/domain/project/application/ProjectServiceTest.java
  src/test/java/studio/studioeye/domain/user_notification/application/UserNotificationServiceTest.java
  src/test/java/studio/studioeye/domain/views/application/ViewsServiceTest.java
Labels: 🔖버전

#46 [TEST]: partner information service 단위 테스트 작성
  src/test/java/studio/studioeye/domain/partner_information/application/PartnerInformationServiceTest.java
Labels: :recycle: 테스트

#45 [TEST]: Request 단위 테스트 작성
  src/test/java/studio/studioeye/domain/request/application/RequestServiceTest.java
Labels: :recycle: 테스트

#47 [TEST]: Project Service 단위 테스트 작성
  src/test/java/studio/studioeye/domain/project/application/ProjectServiceTest.java
Labels: :recycle: 테스트

#48 [TEST]: company information 소개 정보 삭제, 상세 정보 삭제 단위테스트
  src/main/java/studio/studioeye/domain/company_information/application/CompanyInformationService.java
  src/test/java/studio/studioeye/domain/CompanyInformationServiceTest.java
Labels: :bug: 버그, :recycle: 테스트

#49 [TEST]: Project Service 단위 테스트 작성
  src/test/java/studio/studioeye/domain/project/application/ProjectServiceTest.java
Labels: :recycle: 테스트

#51 [TEST]: Request 단위 테스트 작성
  src/main/java/studio/studioeye/domain/request/api/RequestController.java
  src/main/java/studio/studioeye/domain/request/application/RequestService.java
  src/main/java/studio/studioeye/domain/request/dao/AnswerRepository.java
  src/main/java/studio/studioeye/domain/request/domain/Answer.java
  src/main/java/studio/studioeye/domain/request/domain/Request.java
  src/main/java/studio/studioeye/domain/request/dto/request/UpdateRequestCommentServiceDto.java
  src/test/java/studio/studioeye/domain/request/application/RequestServiceTest.java
Labels: :recycle: 테스트

#53 [TEST] Notification 단위 테스트
  src/main/java/studio/studioeye/domain/notification/application/NotificationService.java
  src/main/java/studio/studioeye/domain/notification/dao/EmitterRepository.java
  src/main/java/studio/studioeye/domain/notification/dao/EmitterRepositoryImpl.java
  src/main/java/studio/studioeye/domain/notification/domain/Notification.java
  src/test/java/studio/studioeye/domain/notification/application/NotificationServiceTest.java
Labels: :recycle: 테스트

#56 [TEST]: Project 단위 테스트 커버리지 90%이상 채우기
  src/main/java/studio/studioeye/domain/project/application/ProjectService.java
  src/test/java/studio/studioeye/domain/project/application/ProjectServiceTest.java
Labels: :recycle: 테스트

#58 [TEST]: Recruitment 단위 테스트 커버리지 90%이상 채우기
  src/test/java/studio/studioeye/domain/recruitment/application/RecruitmentServiceTest.java
Labels: :recycle: 테스트

#60 [TEST]: Views 단위 테스트 커버리지 90%이상 채우기
  src/main/java/studio/studioeye/domain/views/api/ViewsController.java
  src/main/java/studio/studioeye/domain/views/application/ViewsService.java
  src/test/java/studio/studioeye/domain/views/application/ViewsServiceTest.java
Labels: :recycle: 테스트

#63 [FEAT]: sonarqube 설정
  build.gradle
Labels: :earth_americas: 인프라
