Repository STUDIO-EYE/STUDIO-EYE-SERVER, pull requests merged in 2024-12, with the labels that each got.

#65 [FEAT]: Request 삭제 시, Notification, UserNotification 삭제
  src/main/java/studio/studioeye/domain/notification/application/NotificationService.java
  src/main/java/studio/studioeye/domain/notification/dao/NotificationRepository.java
  src/main/java/studio/studioeye/domain/request/api/RequestController.java
  src/main/java/studio/studioeye/domain/request/application/RequestService.java
  src/main/java/studio/studioeye/domain/user_notification/application/UserNotificationService.java
  src/main/java/studio/studioeye/domain/user_notification/dao/UserNotificationRepository.java
Labels: :rainbow: 기능

#72 [FIX]: 채용공고 단위 테스트 - 채용상태 Close로 수정
  src/test/java/studio/studioeye/domain/recruitment/application/RecruitmentServiceTest.java
Labels: :bug: 버그, :recycle: 테스트

#73 [Refactor]: FaqServiceTest 리팩토링
  src/test/java/studio/studioeye/domain/faq/application/FaqServiceTest.java
Labels: 🛠️ 리팩토링

#78 [Refactor]: Recruitment 리팩토링
  src/main/java/studio/studioeye/domain/recruitment/application/RecruitmentService.java
  src/main/java/studio/studioeye/domain/recruitment/domain/Recruitment.java
  src/main/java/studio/studioeye/domain/recruitment/domain/Status.java
Labels: 🛠️ 리팩토링

#80 [Refactor]: News 리팩토링
  src/main/java/studio/studioeye/domain/news/api/NewsController.java
  src/main/java/studio/studioeye/domain/news/application/NewsService.java
  src/main/java/studio/studioeye/domain/news/dto/CreateNewsServiceRequestDto.java
Labels: 🛠️ 리팩토링

#83 [REFACTOR]: Project SonarQube 이슈 제거
  src/main/java/studio/studioeye/domain/project/application/ProjectService.java
Labels: 🛠️ 리팩토링

#85 [REFACTOR]: Views SonarQube 이슈 제거
  src/main/java/studio/studioeye/domain/views/api/ViewsController.java
  src/main/java/studio/studioeye/domain/views/application/ViewsService.java
  src/main/java/studio/studioeye/domain/views/domain/Views.java
Labels: 🛠️ 리팩토링

#90 [FEAT]: 메뉴 생성 API 변경
  src/main/java/studio/studioeye/domain/menu/api/MenuController.java
  src/main/java/studio/studioeye/domain/menu/application/MenuService.java
  src/main/java/studio/studioeye/global/exception/error/ErrorCode.java
  src/test/java/studio/studioeye/domain/menu/application/MenuServiceTest.java
Labels: :rainbow: 기능

#91 [Feat]: MenuTitle이 ALL인 경우 예외처리 추가
  src/main/java/studio/studioeye/domain/menu/application/MenuService.java
  src/main/java/studio/studioeye/global/exception/error/ErrorCode.java
Labels: :rainbow: 기능

#88 [TEST]: Notification 단위 테스트 커버리지 90%이상 채우기
  src/test/java/studio/studioeye/domain/notification/application/NotificationServiceTest.java
  src/test/java/studio/studioeye/domain/user_notification/application/UserNotificationServiceTest.java
Labels: :recycle: 테스트

#93 [TEST]: Menu 단위 테스트 커버리지 90%이상 채우기
  src/test/java/studio/studioeye/domain/menu/application/MenuServiceTest.java
Labels: :recycle: 테스트

#96 [Refactor]: 단위테스트 전체 리팩토링, 커버리지 90% 올리기
  src/test/java/studio/studioeye/StudioEyeApplicationTests.java
  src/test/java/studio/studioeye/domain/CompanyInformationServiceTest.java
  src/test/java/studio/studioeye/domain/benefit/application/BenefitServiceTest.java
  src/test/java/studio/studioeye/domain/ceo/application/CeoServiceTest.java
  src/test/java/studio/studioeye/domain/client/application/ClientServiceTest.java
  src/test/java/studio/studioeye/domain/faq/application/FaqServiceTest.java
  src/test/java/studio/studioeye/domain/menu/application/MenuServiceTest.java
  src/test/java/studio/studioeye/domain/news/application/NewsServiceTest.java
  src/test/java/studio/studioeye/domain/notification/application/NotificationServiceTest.java
  src/test/java/studio/studioeye/domain/partner_information/application/PartnerInformationServiceTest.java
  src/test/java/studio/studioeye/domain/project/application/ProjectServiceTest.java
  src/test/java/studio/studioeye/domain/recruitment/application/RecruitmentServiceTest.java
  src/test/java/studio/studioeye/domain/request/application/RequestServiceTest.java
  src/test/java/studio/studioeye/domain/user/application/UserServiceImplTest.java
  src/test/java/studio/studioeye/domain/user_notification/application/UserNotificationServiceTest.java
  src/test/java/studio/studioeye/domain/views/application/ViewsServiceTest.java
Labels: :recycle: 테스트, 🛠️ 리팩토링

#99 [REFACTOR]: CompanyInformation SonarQube 이슈 제거
  src/main/java/studio/studioeye/domain/menu/api/MenuController.java
  src/main/java/studio/studioeye/domain/menu/application/MenuService.java
  src/main/java/studio/studioeye/domain/menu/dto/request/UpdateMenuRequestDto.java
  src/main/java/studio/studioeye/domain/menu/dto/request/UpdateMenuServiceRequestDto.java
Labels: 🛠️ 리팩토링

#101 [REFACTOR]: FAQ SonarQube 이슈 제거
  src/main/java/studio/studioeye/domain/faq/api/FaqController.java
  src/main/java/studio/studioeye/domain/faq/application/FaqService.java
  src/main/java/studio/studioeye/domain/faq/dto/request/CreateFaqServiceRequestDto.java
  src/test/java/studio/studioeye/domain/faq/application/FaqServiceTest.java
Labels: :bug: 버그, :recycle: 테스트, 🛠️ 리팩토링

#103 [REFACTOR]: News SonarQube 이슈 제거
  src/main/java/studio/studioeye/domain/news/api/NewsController.java
  src/main/java/studio/studioeye/domain/news/application/NewsService.java
  src/test/java/studio/studioeye/domain/news/application/NewsServiceTest.java
Labels: :recycle: 테스트, 🛠️ 리팩토링

#105 [REFACTOR]: PartnerInformation SonarQube 이슈 제거
  src/main/java/studio/studioeye/domain/partner_information/application/PartnerInformationService.java
  src/main/java/studio/studioeye/domain/partner_information/domain/PartnerInformation.java
  src/main/java/studio/studioeye/domain/partner_information/dto/request/CreatePartnerInfoRequestDto.java
  src/main/java/studio/studioeye/domain/partner_information/dto/request/CreatePartnerInfoServiceRequestDto.java
  src/main/java/studio/studioeye/domain/partner_information/dto/request/UpdatePartnerInfoRequestDto.java
  src/test/java/studio/studioeye/domain/partner_information/application/PartnerInformationServiceTest.java
Labels: 🛠️ 리팩토링

#107 [REFACTOR]: News SonarQube 이슈 제거
  src/main/java/studio/studioeye/domain/user/domain/User.java
Labels: 🛠️ 리팩토링

#111 [REFACTOR]: Views SonarQube 이슈 제거
  src/main/java/studio/studioeye/domain/views/application/ViewsService.java
  src/main/java/studio/studioeye/global/exception/error/ErrorCode.java
Labels: 🛠️ 리팩토링

#114 [FEAT]: 아트워크 에러 메세지 수정
  src/main/java/studio/studioeye/global/exception/error/ErrorCode.java
Labels: :rainbow: 기능
